
# **AirQ_Part2_047** — Assignment 2 (ETL + OLAP with Atoti)

- This notebook orchestrates Assignment 2.
- All SQL must live in external `.sql` files under `ddl/`, `etl/`, and `sql/`. 
- All MDX must live in external `.mdx` files under `mdx/`.

**Final folder layout (per‑group, self‑contained)**

```
BI_Projects/
  DWH2_xxx/
    csv/       # 15 OLTP CSV files
    ddl/       # DDL only (staging, warehouse)
    etl/       # ETL steps: a2_etl*.sql files
    mdx/       # MDX-queries in .mdx files: a2_q{NN}_{A|B}.mdx
    mdx_out/   # CSV files with the results of MDX-queries
    pdf/       # PDF files with dashboard exports: a2_q{NN}.pdf
    sql/       # SQL-queries in .sql files: a2_q{NN}_{A|B}.sql
    sqldump/   # Export produced by pg_dump
    AirQ_Part2_xxx.ipynb
    group_xxx.txt
    Report_Part2_Group_xxx.pdf
```
> Replace `xxx` in your file names with your **three‑digit** group number.

## Contents
1. Configuration & preflight (group, paths)  
2. Database connection
3. Reset and create staging schema (`stg2_047`) from DDL file 
4. Load CSVs into stg2_047 (order-sensitive)  
5. Reset and create warehouse (`dwh2_047`) from DDL file 
6. ETL runner (executes `etl/a2_etl*.sql`)  
7. SQL queries
8. Atoti setup and build the OLAP cube (scaffold)
9. Define hierarchies and measures
10. MDX queries
11. Batch executor: run all .mdx → CSV (+ an index)
12. Create database dump
13. Submission checklist


## 1) Configuration & preflight

In [59]:
# === Parameters ===
# XXX = "001"               # # three digits, e.g. "007"
# ...
# XXX = "031"               # # three digits, e.g. "007"
# ...
# XXX = "071"               # # three digits, e.g. "007"
# ...
# XXX = "199"               # # three digits, e.g. "007"
XXX = "047"               # # three digits, e.g. "007"

VERBOSE_SQL = False             # print progress when running .sql files
LOAD_ORDER_CSV = []             # or fill later
LOAD_ORDER_DATA = []            # or fill later

In [60]:
import re, time
import shutil, subprocess, os
import json, hashlib

from pathlib import Path
from getpass import getpass
from urllib.parse import quote_plus
from datetime import datetime, timezone

import pandas as pd
import sqlalchemy as sa
import sqlparse
from sqlalchemy import create_engine, text, engine

import atoti as tt

In [61]:
!pip show atoti

WARNING: Package(s) not found: atoti

In [62]:
# === Toggles & paths ===
root_dir = Path.cwd()
csv_dir = root_dir / "csv"
ddl_dir = root_dir / "ddl"
etl_dir = root_dir / "etl"
mdx_dir = root_dir / "mdx"
mdx_out_dir = root_dir / "mdx_out"
sql_dir = root_dir / "sql"
sqldump_dir = root_dir / "sqldump"

SCHEMA_STG = f"stg2_{XXX}"
SCHEMA_DWH = f"dwh2_{XXX}"

# files we expect in the ddl subfolder
STG2_RESET  = ddl_dir / f"airq_reset_stg2_{XXX}.sql"
STG2_CREATE = ddl_dir / f"airq_create_stg2_{XXX}.sql"
DWH2_RESET  = ddl_dir / f"airq_reset_dwh2_{XXX}.sql"
DWH2_CREATE = ddl_dir / f"airq_create_dwh2_{XXX}.sql"

print("CSV dir:", csv_dir)
print("DDL dir:", ddl_dir)
print("ETL dir:", etl_dir)
print("MDX dir:", mdx_dir)
print("MDX_out dir:", mdx_out_dir)
print("SQL dir:", sql_dir)
print("SQLdump dir:", sqldump_dir)

CSV dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\csv
DDL dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\ddl
ETL dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\etl
MDX dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\mdx
MDX_out dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\mdx_out
SQL dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\sql
SQLdump dir: D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\sqldump


## 2) Make database connection

In [64]:
# === Minimal config & connect ===
DB_USER = f"grp_{XXX}"
DB_NAME = "airq"
DB_HOST = "localhost"
DB_PORT = "5432"

# a password is asked once per run; enter empty password if your local pg_hba allows trust/peer
pw = getpass(f"Password for {DB_USER}@{DB_HOST}:{DB_PORT}/{DB_NAME} (leave empty if not needed): ")
DSN = f"postgresql+psycopg2://{DB_USER}:{quote_plus(pw)}@{DB_HOST}:{DB_PORT}/{DB_NAME}" if pw \
      else f"postgresql+psycopg2://{DB_USER}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

def _mask_dsn(dsn: str) -> str:
    try:
        return str(engine.make_url(dsn).set(password="***"))
    except Exception:
        return re.sub(r"://([^:@]+)(?::[^@]*)?@", r"://\\1:***@", dsn)

engine = create_engine(DSN, future=True, pool_pre_ping=True)
print("Connecting via:", _mask_dsn(DSN))

with engine.begin() as conn:
    # best-effort: set the role if it exists; don't crash if not
    try:
        conn.exec_driver_sql(f"SET ROLE grp_{XXX}")
        print(f"SET ROLE grp_{XXX} ✓")
    except Exception as e:
        print(f"(no SET ROLE: {e.__class__.__name__})")
    who = conn.exec_driver_sql("select current_user").scalar_one()
    print("current_user:", who)

Password for grp_047@localhost:5432/airq (leave empty if not needed):  ········

Connecting via: postgresql+psycopg2://\1:***@localhost:5432/airq
SET ROLE grp_047 ✓
current_user: grp_047

In [65]:
def run_sqlscript(
    path: str,
    *,
    engine,
    progress: bool = True,      # progress/verbosity- show progress OR keep output quiet
    add_search_path: bool = False,
    schema_dwh: str | None = None,
    schema_stg: str | None = None,
    title: str | None = None,      # optional title
    strip_psql_meta: bool = True,  # psql meta stripping
):
    """
    Execute all statements in a .sql file.
    - Returns the LAST result set as a pandas.DataFrame if any statement returns rows; else None.
    - Set progress=False to suppress progress/header prints (great for check scripts).
    """

    raw = Path(path).read_text(encoding="utf-8")

    # Strip psql meta-commands (e.g., \i, \set) if requested
    if strip_psql_meta:
        raw = "\n".join(
            line for line in raw.splitlines()
            if not line.lstrip().startswith("\\")
        )

    # Optional search_path prologue
    prologue = ""
    if add_search_path:
        schs = [s for s in (schema_dwh, schema_stg) if s]
        if schs:
            prologue = f"SET search_path TO {', '.join(schs)};\n"

    script = prologue + raw
    stmts = [s.strip() for s in sqlparse.split(script) if s and s.strip(" ;\n\t")]

    if progress:
        hdr = f"▶ {title}" if title else "▶ Running SQL script"
        print(f"{hdr}: {path} ({len(stmts)} statements)")
    t0 = time.time()

    last_df = None
    with engine.begin() as conn:
        for i, stmt in enumerate(stmts, start=1):
            if not stmt:
                continue
            start = time.time()
            try:
                if progress:
                    preview = " ".join(stmt.split())[:120]
                    print(f"  {i:>3}: {preview} ...")

                cursor = conn.exec_driver_sql(stmt)

                if cursor.returns_rows:
                    rows = cursor.fetchall()
                    cols = cursor.keys()
                    last_df = pd.DataFrame(rows, columns=cols)

                if progress:
                    print(f"       OK ({time.time() - start:.3f}s)")

            except Exception as e:
                # Raise with a helpful preview even when progress=False
                preview = " ".join(stmt.split())[:160]
                raise RuntimeError(
                    f"SQL error in statement #{i}: {preview}"
                ) from e

    if progress:
        print(f"✅ Done in {time.time() - t0:.2f}s")

    return last_df

## 3) Reset and create **staging schema** (`stg2_xxx`) from DDL file

In [66]:
print(f"== STAGING-ONLY RESET: stg2_{XXX} ==")
try:
    for p in (STG2_RESET, STG2_CREATE):
        run_sqlscript(p, engine=engine, progress=VERBOSE_SQL)
except Exception as e:
    print(f"!! Reset & create failed: {e}")
    raise

== STAGING-ONLY RESET: stg2_047 ==

## 4) Load CSV → `stg2_xxx` with Pandas `.to_sql()`

In [67]:
def load_folder_to_stg(
    folder_name: str,
    engine,
    SCHEMA_STG: str,
    load_order=None,
    if_exists: str = "append",
    chunksize: int = 20000,
):
    global root_dir  # expected to be defined earlier
    src_dir = Path(root_dir) / folder_name
    if not src_dir.exists():
        raise FileNotFoundError(f"Folder not found: {src_dir}")

    def load_one(name: str):
        path = src_dir / f"{name}.csv"
        if not path.exists():
            print("Missing CSV:", path.name)
            return 0
        df = pd.read_csv(
            path,
            na_values=["\\N"],
            keep_default_na=False,
            low_memory=False,
        )
        # Convert any *...from / ...to / ...at* to DATE
        for col in df.columns:
            col_l = col.lower()
            if col_l.endswith(("from", "to", "at")):
                df[col] = pd.to_datetime(df[col], format="%Y-%m-%d", errors="coerce").dt.date
        # Write
        df.to_sql(
            name,
            con=engine,
            schema=SCHEMA_STG,
            if_exists=if_exists,
            index=False,
            method="multi",
            chunksize=chunksize,
        )
        print(f"Loaded {len(df):,} rows → {SCHEMA_STG}.{name}")
        return len(df)

    if not load_order:
        discovered = sorted([p.stem for p in src_dir.glob("*.csv")])
        print("No order set yet. CSVs found:", discovered)
        return

    t0 = time.time()
    total = 0
    for name in load_order:
        total += load_one(name)
    print(f"⏱️ Total load time: {time.time() - t0:.2f} seconds · {total:,} rows")

In [68]:
# Loading of original 15 CSV files in the correct order
LOAD_ORDER_CSV = ["tb_servicetype","tb_role","tb_employee","tb_country","tb_city","tb_readingmode",
                  "tb_alert","tb_param","tb_paramalert","tb_sensortype","tb_paramsensortype","tb_sensordevice",
                  "tb_weather","tb_serviceevent","tb_readingevent"]

load_folder_to_stg("csv", engine, SCHEMA_STG, load_order=LOAD_ORDER_CSV,  if_exists="append")

Loaded 24 rows → stg2_047.tb_servicetype
Loaded 16 rows → stg2_047.tb_role
Loaded 484 rows → stg2_047.tb_employee
Loaded 20 rows → stg2_047.tb_country
Loaded 36 rows → stg2_047.tb_city
Loaded 8 rows → stg2_047.tb_readingmode
Loaded 4 rows → stg2_047.tb_alert
Loaded 30 rows → stg2_047.tb_param
Loaded 120 rows → stg2_047.tb_paramalert
Loaded 12 rows → stg2_047.tb_sensortype
Loaded 115 rows → stg2_047.tb_paramsensortype
Loaded 627 rows → stg2_047.tb_sensordevice
Loaded 26,316 rows → stg2_047.tb_weather
Loaded 22,720 rows → stg2_047.tb_serviceevent
Loaded 985,573 rows → stg2_047.tb_readingevent
⏱️ Total load time: 144.09 seconds · 1,036,105 rows

## 5) Reset and create **warehouse** (`dwh2_xxx`) from DDL file

In [69]:
print(f"== DWH-ONLY RESET: dwh2_{XXX} ==")
try:
    for p in (DWH2_RESET, DWH2_CREATE):
        run_sqlscript(p, engine=engine, progress=VERBOSE_SQL)
except Exception as e:
    print(f"!! Reset & create failed: {e}")
    raise

== DWH-ONLY RESET: dwh2_047 ==


## 6) SQL-first ETL — run all files in etl/

We execute **all** files matching `etl/a2_etl*.sql` in lexicographic order. Every ETL file must begin with `SET search_path TO dwh2_xxx, stg2_xxx;`

In [70]:
steps = sorted(etl_dir.glob("a2_etl*.sql"))
if not steps:
    print("No ETL step files found in etl/ (expected a2_etl*.sql).")
else:
    for s in steps:
        run_sqlscript(s, engine=engine, progress=VERBOSE_SQL)

## 7) SQL-queries

In [71]:
# Business question Q31 (example)
df = run_sqlscript("sql/a2_q31.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

    city_name P95 Recorded Value (2023)
0      Prague                    161.46
1     Hamburg                    155.68
2      Athens                    149.73
3      London                    140.05
4   Edinburgh                    134.69
5    Istanbul                    131.56
6  Copenhagen                    131.55
7   Stuttgart                    130.54
8       Kazan                    128.07
9   Barcelona                    126.69

In [72]:
# Business question Q32 (example)
df = run_sqlscript("sql/a2_q32.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

        city_name Data Volume (KB) 2024
0        Istanbul                803441
1          London                330327
2          Moscow                257108
3          Berlin                224658
4  St. Petersburg                215185
5           Paris                196835
6            Rome                188638
7             Ufa                174256
8      Copenhagen                148863
9          Vienna                146300

In [73]:
# Business question Q33 (example)
df = run_sqlscript("sql/a2_q33.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

      country_name month_name Avg Data Quality
0          Austria        Sep             3.58
1          Belarus        Sep             3.24
2          Belgium        Sep             3.18
3          Croatia        Jun             3.60
4   Czech Republic        Apr             3.24
5          Denmark        Jun             3.48
6          Finland        May             3.70
7           France        Apr             3.09
8          Germany        Sep             3.12
9           Greece        Aug             3.12
10         Hungary        Aug             3.43
11           Italy        Aug             3.24
12     Netherlands        Apr             3.26
13          Poland        Jan             3.29
14          Russia        Jun             3.29
15          Serbia        Apr             3.40
16           Spain        Dec             3.18
17          Sweden        Oct             3.21
18          Turkey        Apr             3.26
19  United Kingdom        Nov             3.42

## 7.1) SQL-queries - Student A

In [74]:
# Business question Q01
df = run_sqlscript("sql/a2_q01_A.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

           country  jan_2024  feb_2024  mar_2024
0          Austria        14         6         8
1          Belgium         6         2         4
2          Croatia         6         2         5
3   Czech Republic         7         3         5
4          Denmark         1         6         7
5          Finland         2         2         1
6           France        16        14        14
7          Germany        25        18        27
8           Greece         9         7        11
9          Hungary         7         3         7
10           Italy        10         6         6
11          Poland         4         1         2
12          Russia        24        25        28
13           Spain         6         2         4
14          Sweden         8         6        13
15          Turkey        34        24        27
16  United Kingdom         6         8        13

In [75]:
# Business question Q05
df = run_sqlscript("sql/a2_q05_A.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

              param_category year_2023 year_2024
0                 Biological   6328259   6298621
1                        Gas   5599952   5597083
2                Heavy Metal   4961428   4955113
3         Particulate matter   5257962   5267659
4  Volatile Organic Compound   4962229   4974177

In [76]:
# Business question Q08
df = run_sqlscript("sql/a2_q08_A.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

          country avg_data_quality_2024
0         Austria    2.9872878915662651
1          France    3.0066534486434109
2         Germany    3.0108574103448276
3           Italy    3.0071215112994350
4          Russia    2.9952830740740741
5          Sweden    3.0119288645833333
6          Turkey    2.9976046214689266
7  United Kingdom    3.0025157387005650

In [77]:
# Business question Q15
df = run_sqlscript("sql/a2_q15_A.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

   country  exceed_days_2023  exceed_days_2024
0  Belarus              1537              1474
1   Greece              3194              3128
2   Russia             12093             12074
3   Serbia               798               804
4   Turkey             12015             11798

In [78]:
# Business question Q26
df = run_sqlscript("sql/a2_q26_A.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

           country         avg_pm1_2024         avg_no2_2024
0          Austria  38.3559981944444444  65.8324951944444444
1          Belarus  38.2785001666666667  58.6738946666666667
2          Belgium  35.7242761666666667                    0
3          Croatia  37.8721807500000000  69.8114400833333333
4   Czech Republic  39.4353025833333333  70.9159849583333333
5          Denmark  41.4332272500000000                    0
6          Finland  36.1021827500000000  60.5004400833333333
7           France  37.6151321111111111  64.7968658333333333
8          Germany  40.4154846833333333  65.2264863958333333
9           Greece  41.4302460833333333  70.0553228333333333
10         Hungary  36.1386154166666667  65.5492530833333333
11           Italy  37.0027780000000000  60.8766339166666667
12     Netherlands  42.4172496666666667  69.6067386666666667
13          Poland  36.5899360000000000  61.3183266666666667
14          Russia  36.4282167083333333  61.7347991250000000
15          Serbia  32.4725564166666667  55.5563999166666667
16           Spain                    0  65.8468434166666667
17          Sweden  34.2111541666666667  58.7688097916666667
18          Turkey  38.0900564166666667  70.7959875833333333
19  United Kingdom  37.5549280833333333  66.0155880416666667

## 7.2) SQL-queries - Student B

In [84]:
# Business question Q2. For parameter O3, show Missing Days in Austria by City × Month for Q1 of 2023. Return Austrian
# Cities on rows and the first three months of 2023 (Jan–Mar) on columns.
df = run_sqlscript("sql/a2_q02_B.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

       city  jan_2023  feb_2023  mar_2023
0      Graz        11         4         2
1  Salzburg         3         5         4
2    Vienna         6         2         2

In [85]:
# Business question Q7. For parameter PM10, show Avg Recorded Value and P95 Recorded Value by Country for 2023.
# Return Countries on rows and two columns—Avg Recorded Value and P95 Recorded Value for the year 2023.
df = run_sqlscript("sql/a2_q07_B.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

           country             pm10_avg              pm10_p95
0          Austria  81.9452968611111111  166.7367666666666667
1          Belarus  74.5365324166666667  163.6457750000000000
2          Belgium  77.5215955833333333  177.4433000000000000
3          Croatia  79.7458564166666667  195.1960250000000000
4   Czech Republic  79.0951547916666667  177.4448000000000000
5          Denmark  76.5748207500000000  187.2309916666666667
6          Finland  74.2843906666666667  149.7598083333333333
7           France  77.2389318333333333  163.1479027777777778
8          Germany  80.0958445833333333  172.5016183333333333
9           Greece  95.0700151666666667  202.5493166666666667
10         Hungary  79.4340142500000000  157.6461083333333333
11           Italy  74.8189528750000000  160.7235333333333333
12          Poland  76.1107295000000000  168.8538250000000000
13          Russia  78.0371567083333333  178.0393270833333333
14          Serbia  70.6274145833333333  125.8902666666666667
15           Spain  75.9082608333333333  168.0513750000000000
16          Sweden  76.1595957500000000  149.3673833333333333
17          Turkey  80.6191925833333333  169.3863333333333333
18  United Kingdom  79.1158287500000000  190.9634958333333333

In [86]:
# Business question Q10. For 2024, list the Top 10 Countries by Avg Data Quality. Return the 10 countries with the highest
# values on rows (highest . lowest) and one column with Avg Data Quality for 2024.
df = run_sqlscript("sql/a2_q10_B.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

          country   data_quality_2024
0         Belarus  3.0413258209876543
1         Croatia  3.0156915344827586
2          Sweden  3.0119288645833333
3         Finland  3.0109282857142857
4         Germany  3.0108574103448276
5           Italy  3.0071215112994350
6          Poland  3.0067860333333333
7          France  3.0066534486434109
8          Serbia  3.0054633549382716
9  United Kingdom  3.0025157387005650

In [87]:
# Business question Q17. Show Avg Data Quality by Country for 2023 and 2024. Return Countries on rows and two
# columns—2023 and 2024 values of Avg Data Quality.
df = run_sqlscript("sql/a2_q17_B.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

           country   data_quality_2023   data_quality_2024
0          Austria  2.9970856425702811  2.9872878915662651
1          Belarus  3.0486171882716049  3.0413258209876543
2          Belgium  3.0155145769230769  2.9971552820512821
3          Croatia  3.0428296839080460  3.0156915344827586
4   Czech Republic  2.9955159933333333  2.9905771183333333
5          Denmark  3.0217912241379310  3.0003959137931034
6          Finland  2.9838187797619048  3.0109282857142857
7           France  2.9771062412790698  3.0066534486434109
8          Germany  3.0008475241379310  3.0108574103448276
9           Greece  2.9988198103448276  2.9956242528735632
10         Hungary  3.0049301000000000  2.9990285388888889
11           Italy  3.0065684887005650  3.0071215112994350
12     Netherlands  3.0013755555555556  2.9992694166666667
13          Poland  3.0038912888888889  3.0067860333333333
14          Russia  2.9982031367521368  2.9952830740740741
15          Serbia  2.9995599753086420  3.0054633549382716
16           Spain  3.0179219851190476  2.9942931398809524
17          Sweden  3.0190483616071429  3.0119288645833333
18          Turkey  3.0086489604519774  2.9976046214689266
19  United Kingdom  3.0021892274011299  3.0025157387005650

In [88]:
# Business question Q29. Show Data Volume (KB) by Country in Eastern Europe for 2023 and 2024. Return Eastern
# European countries on rows and two columns - 2023 and 2024 totals of Data Volume (KB).
df = run_sqlscript("sql/a2_q29_B.sql", engine=engine, progress=VERBOSE_SQL)
display(df)

   country        dvolume_kb_2023        dvolume_kb_2024
0  Belarus  1316.3703703703703704  1315.3611111111111111
1   Greece  2060.0862068965517241  2026.6034482758620690
2   Russia  2780.6460113960113960  2777.0242165242165242
3   Serbia  1322.4012345679012346  1318.0370370370370370
4   Turkey  6962.1737288135593220  6983.3926553672316384

## 8) Atoti setup and build cube (scaffold)

In [89]:
os.environ.pop("JAVA_HOME", None)  # let Atoti use its own JDK via jdk4py

# Start a new Atoti session
session = tt.Session.start()

# URL to the Atoti web app
session.url

'http://localhost:57084'

In [90]:
def upsert_table(session, name, df, *, keys=None, defaults=None, dtypes=None):
    if name in session.tables.keys():
        t = session.tables[name]
        t.drop()  # delete all rows, keep schema
        if defaults:  # non-nullability even for existing tables
            for col, val in defaults.items():
                t[col].default_value = val  # set after creation too
        t.load(df)
    else:
        t = session.read_pandas(
            df,
            table_name=name,
            keys=keys or (),
            default_values=defaults or {},   # set at creation time
            data_types=dtypes or {},
        )
    return t

In [91]:
# Load star-schema tables to DataFrames
df_time   = pd.read_sql(f"SELECT * FROM dwh2_{XXX}.dim_timemonth", engine)
df_city   = pd.read_sql(f"SELECT * FROM dwh2_{XXX}.dim_city", engine)
df_param  = pd.read_sql(f"SELECT * FROM dwh2_{XXX}.dim_param", engine)
df_alert  = pd.read_sql(f"SELECT * FROM dwh2_{XXX}.dim_alertpeak", engine)
df_fact   = pd.read_sql(f"SELECT * FROM dwh2_{XXX}.ft_param_city_month", engine)

time_store  = upsert_table(session, "dim_timemonth", df_time,
                           keys=["month_key"],
                           defaults={"year_num": 0, "quarter_num": 0, "month_name": "Unknown"},
                           dtypes={"year_num": "int", "quarter_num": "int"})

city_store  = upsert_table(session, "dim_city", df_city,
                           keys=["city_key"],
                           defaults={"region_name": "Unknown", "country_name": "Unknown", "city_name": "Unknown"})

param_store = upsert_table(session, "dim_param", df_param,
                           keys=["param_key"],
                           defaults={"purpose": "Unknown", "category": "Unknown", "param_name": "Unknown"})

ap_store    = upsert_table(session, "dim_alertpeak", df_alert,
                           keys=["alertpeak_key"],
                           defaults={"alert_level_name": "None"})

fact_store = upsert_table(session, "ft_param_city_month", df_fact, 
                          keys=["ft_pcm_key"], 
                          defaults={"month_key": 0, "city_key": 0, "param_key": 0, "alertpeak_key": 1000,  # FKs
                                    "reading_events_count": 0, "devices_reporting_count": 0, 
                                    "data_volume_kb_sum": 0, "recordedvalue_avg": 0.0, "recordedvalue_p95": 0.0, 
                                    "exceed_days_any": 0, "data_quality_avg": 0.0, "missing_days": 0, 
                                   }, 
                          dtypes={"month_key": "int", "city_key": "int", 
                                  "param_key": "int", "alertpeak_key": "int", 
                                  "reading_events_count": "int", "devices_reporting_count": "int", 
                                  "data_volume_kb_sum": "int", "recordedvalue_avg": "float", 
                                  "recordedvalue_p95": "float", "exceed_days_any": "int", 
                                  "data_quality_avg": "float", "missing_days": "int", 
                                 },
                         )

# Define joins once per fresh session - can re-run the cell without redefining joins
if not getattr(session, "_airq_joins_done", False):
    fact_store.join(time_store,   fact_store["month_key"]     == time_store["month_key"])
    fact_store.join(city_store,   fact_store["city_key"]      == city_store["city_key"])
    fact_store.join(param_store,  fact_store["param_key"]     == param_store["param_key"])
    fact_store.join(ap_store,     fact_store["alertpeak_key"] == ap_store["alertpeak_key"])
    session._airq_joins_done = True

# Create or reuse the cube
cube_name = "AirQ Cube"
cube = (
    session.cubes[cube_name]
    if cube_name in session.cubes.keys()
    else session.create_cube(fact_store, cube_name, mode="manual")
)

# Access cube components
m, h, l = cube.measures, cube.hierarchies, cube.levels

cube

## 9) Define hierarchies and measures
Define explicit hierarchies in Atoti:

1) Time: Year → Quarter → Month,
2) Geo: Region → Country → City,
3) Param: Purpose → Category → Param,
4) Alert: Level (sorted by rank).

In [92]:
# TODO: define hierarchies
# h["Time"]  = [...]
# h["Geo"]   = [...]
# h["Param"] = [...]
# h["Alert"] = [...]

h["Time"] = [time_store["year_num"], time_store["quarter_num"], time_store["month_name"]]
h["Geo"] = [city_store["region_name"], city_store["country_name"], city_store["city_name"]]
h["Param"] = [param_store["purpose"], param_store["category"], param_store["param_name"]]
h["Alert"] = [ap_store["alert_level_name"]]

# TODO: define measures
# m["Reading Events"]        =   ...      # fully additive
# m["Devices Reporting"]     =   ...      # fully additive
# m["Data Volume (KB)"]      =   ...      # fully additive
# m["Missing Days"]          =   ...      # fully additive
# m["Exceed Days (any)"]     =   ...      # fully additive
# m["Avg Recorded Value"]    =   ...      # semi-additive
# m["P95 Recorded Value"]    =   ...      # semi-additive
# m["Avg Data Quality"]      =   ...      # semi-additive

m["Reading Events"] = tt.agg.sum(fact_store["reading_events_count"])
m["Devices Reporting"] = tt.agg.sum(fact_store["devices_reporting_count"])
m["Data Volume (KB)"] = tt.agg.sum(fact_store["data_volume_kb_sum"])
m["Missing Days"] = tt.agg.sum(fact_store["missing_days"])
m["Exceed Days (any)"] = tt.agg.sum(fact_store["exceed_days_any"])

m["Avg Recorded Value"] = tt.agg.mean(fact_store["recordedvalue_avg"])
m["P95 Recorded Value"] = tt.agg.mean(fact_store["recordedvalue_p95"])
m["Avg Data Quality"] = tt.agg.mean(fact_store["data_quality_avg"])

In [93]:
# order months as in calendar, not alphabetically
month_lvl = cube.hierarchies["Time"]["month_name"]
month_lvl.order = tt.CustomOrder(first_elements=["Jan","Feb","Mar","Apr","May","Jun",
                                                 "Jul","Aug","Sep","Oct","Nov","Dec"])

In [94]:
# order alert levels from least to most harmful
alert_lvl = cube.hierarchies["Alert"]["alert_level_name"]
alert_lvl.order = tt.CustomOrder(first_elements=["None", "Yellow", "Orange", "Red", "Crimson"])

In [95]:
cube

In [96]:
print("\nHierarchies and their levels:")
for h_name, hierarchy in cube.hierarchies.items():
    level_names = [getattr(level, "name", str(level)) for level in hierarchy]
    print(f" - {h_name} → levels: {level_names}")

print("\nMeasures:")
for m in cube.measures.keys():
    print("  -", m)

Hierarchies and their levels:
 - ('dim_timemonth', 'Time') → levels: ['year_num', 'quarter_num', 'month_name']
 - ('dim_param', 'Param') → levels: ['purpose', 'category', 'param_name']
 - ('dim_alertpeak', 'Alert') → levels: ['alert_level_name']
 - ('dim_city', 'Geo') → levels: ['region_name', 'country_name', 'city_name']

Measures:
  - Avg Data Quality
  - P95 Recorded Value
  - Avg Recorded Value
  - Devices Reporting
  - contributors.COUNT
  - Exceed Days (any)
  - Reading Events
  - Data Volume (KB)
  - update.TIMESTAMP
  - Missing Days

## 10) MDX queries

In [97]:
# MDX cell magic: let us write MDX code like this:
#   %%mdx
#   SELECT ... FROM [AirQ Cube]
#
# Requirements: a live `session` from atoti and the cube already created.

from IPython.core.magic import register_cell_magic
from IPython.display import display

@register_cell_magic
def mdx(line, cell):
    """Run MDX in this cell and display a DataFrame.
    Usage:
        %%mdx
        SELECT ...
        FROM [AirQ Cube]
    """
    q = cell.strip()
    df = session.query_mdx(q)   # Atoti returns levels on index, measures as columns
    return df                   # df = _

### 10.1) Business question Q31 (example)

In [98]:
%%mdx

-- 31. For parameter O3, list the Top 10 Cities by P95 Recorded Value for 2023.
-- Return the 10 cities with the highest values on rows (highest → lowest) and one column with P95 Recorded Value for 2023.
SELECT
  { [Measures].[P95 Recorded Value] } ON COLUMNS,
  TOPCOUNT(
    NONEMPTY(
      [dim_city].[Geo].[city_name].Members,
      [Measures].[P95 Recorded Value]
    ),
    10, [Measures].[P95 Recorded Value]
  ) ON ROWS
FROM [AirQ Cube]
WHERE (
  [dim_timemonth].[Time].[year_num].&[2023],
  [dim_param].[Param].[param_name].&[O3]
)

                                         P95 Recorded Value
region_name    country_name   city_name
Central Europe Czech Republic Prague                 161.46
               Germany        Hamburg                155.68
Eastern Europe Greece         Athens                 149.73
Western Europe United Kingdom London                 140.05
                              Edinburgh              134.69
Eastern Europe Turkey         Istanbul               131.56
Western Europe Denmark        Copenhagen             131.55
Central Europe Germany        Stuttgart              130.54
Eastern Europe Russia         Kazan                  128.07
Western Europe Spain          Barcelona              126.69

### 10.2) Business question Q32 (example)

In [99]:
%%mdx 

-- 32. For 2024, show Data Volume (KB) by City for category ‘Volatile Organic Compound’, and list the Top 10 cities.
-- Return the Top 10 cities on rows (highest -> lowest) and one column with Data Volume (KB) for 2024, limited to the Volatile Organic Compound category.
SELECT
  { [Measures].[Data Volume (KB)] } ON COLUMNS,
  TOPCOUNT(
    NONEMPTY([dim_city].[Geo].[city_name].Members, [Measures].[Data Volume (KB)]),
    10, [Measures].[Data Volume (KB)]
  ) ON ROWS
FROM (
  SELECT ( [dim_timemonth].[Time].[year_num].&[2024] ) ON 0 FROM (
    SELECT (
      FILTER(
        [dim_param].[Param].[param_name].Members,
        ANCESTOR(
          [dim_param].[Param].CurrentMember,
          [dim_param].[Param].[category]
        ).Name = "Volatile Organic Compound"
      )
    ) ON 0 FROM [AirQ Cube]
  )
)

                                             Data Volume (KB)
region_name    country_name   city_name
Eastern Europe Turkey         Istanbul                803,441
Western Europe United Kingdom London                  330,327
Eastern Europe Russia         Moscow                  257,108
Central Europe Germany        Berlin                  224,658
Eastern Europe Russia         St. Petersburg          215,185
Western Europe France         Paris                   196,835
               Italy          Rome                    188,638
Eastern Europe Russia         Ufa                     174,256
Western Europe Denmark        Copenhagen              148,863
Central Europe Austria        Vienna                  146,300

### 10.3) Business question Q33 (example)

In [100]:
%%mdx

-- 33. For parameter PM4 in 2024, return for each Country the Month with the highest Avg Data Quality.
-- Return one row per Country × Month (the month with the highest Avg Data Quality in 2024) and one column with Avg Data Quality.
SELECT
  { [Measures].[Avg Data Quality] } ON COLUMNS,
  NON EMPTY
    GENERATE(
      [dim_city].[Geo].[country_name].Members,
      TOPCOUNT(
        CROSSJOIN(
          { [dim_city].[Geo].CurrentMember },
          Descendants(
            [dim_timemonth].[Time].[year_num].&[2024],
            [dim_timemonth].[Time].[month_name]
          )
        ),
        1, [Measures].[Avg Data Quality]
      )
    ) ON ROWS
FROM [AirQ Cube]
WHERE ( [dim_param].[Param].[param_name].&[PM4] )

                                                              Avg Data Quality
region_name    country_name   year_num quarter_num month_name
Central Europe Austria        2024     3           Sep                    3.58
               Croatia        2024     2           Jun                    3.60
               Czech Republic 2024     2           Apr                    3.24
               Germany        2024     3           Sep                    3.12
               Hungary        2024     3           Aug                    3.43
               Poland         2024     1           Jan                    3.29
Eastern Europe Belarus        2024     3           Sep                    3.24
               Greece         2024     3           Aug                    3.12
               Russia         2024     2           Jun                    3.29
               Serbia         2024     2           Apr                    3.40
               Turkey         2024     2           Apr                    3.26
Western Europe Belgium        2024     3           Sep                    3.18
               Denmark        2024     2           Jun                    3.48
               Finland        2024     2           May                    3.70
               France         2024     2           Apr                    3.09
               Italy          2024     3           Aug                    3.24
               Netherlands    2024     2           Apr                    3.26
               Spain          2024     4           Dec                    3.18
               Sweden         2024     4           Oct                    3.21
               United Kingdom 2024     4           Nov                    3.42

# Student A

### 10.4) Business question Q07

In [101]:
%%mdx 
-- 07. For parameter PM10, show Avg Recorded Value and P95 Recorded Value by Country for 2023. 
-- Return Countries on rows and two columns - Avg Recorded Value and P95 Recorded Value - for the year 2023. 

SELECT
  { [Measures].[Avg Recorded Value], [Measures].[P95 Recorded Value] } ON COLUMNS,
  [dim_city].[Geo].[country_name].Members ON ROWS
FROM [AirQ Cube]
WHERE (
    [dim_param].[Param].[param_name].&[PM10],
    [dim_timemonth].[Time].[year_num].&[2023]
)

                              Avg Recorded Value P95 Recorded Value
region_name    country_name
Central Europe Austria                     81.95             166.74
               Croatia                     79.75             195.20
               Czech Republic              79.10             177.44
               Germany                     80.10             172.50
               Hungary                     79.43             157.65
               Poland                      76.11             168.85
Eastern Europe Belarus                     74.54             163.65
               Greece                      95.07             202.55
               Russia                      78.04             178.04
               Serbia                      70.63             125.89
               Turkey                      80.62             169.39
Unknown        Unknown
Western Europe Belgium                     77.52             177.44
               Denmark                     76.57             187.23
               Finland                     74.28             149.76
               France                      77.24             163.15
               Italy                       74.82             160.72
               Netherlands
               Spain                       75.91             168.05
               Sweden                      76.16             149.37
               United Kingdom              79.12             190.96

### 10.5) Business question Q08

In [102]:
%%mdx 
-- 08. For 2024, show Avg Data Quality by Country, but only for countries whose 2024 year-total Devices Reporting is at least 2000. 
-- Return Countries on rows (filtered to Devices Reporting >= 2000) and one column with Avg Data Quality for the year 2024.

WITH
MEMBER [Measures].[Avg_data_quality_2024] AS
    ([Measures].[Avg Data Quality], [dim_timemonth].[Time].[year_num].&[2024])

SELECT
  { [Measures].[Avg_data_quality_2024] } ON COLUMNS,
  FILTER(
    [dim_city].[Geo].[country_name].Members,
    ([Measures].[Devices Reporting], 
     [dim_timemonth].[Time].[year_num].&[2024], 
     [dim_city].[Geo].CurrentMember) >= 2000
  ) ON ROWS
FROM [AirQ Cube]

                              Avg_data_quality_2024
region_name    country_name
Central Europe Austria            2.987287890121161
               Germany           3.0108574101294594
Eastern Europe Russia            2.9952830752925657
               Turkey             2.997604619985246
Western Europe France            3.0066534491010413
               Italy              3.007121510088107
               Sweden            3.0119288648877824
               United Kingdom     3.002515734925782

### 10.6) Business question Q10

In [103]:
%%mdx 
-- 10. For 2024, list the Top 10 Countries by Avg Data Quality. 
-- Return the 10 countries with the highest values on rows (highest → lowest) and one column with Avg Data Quality for 2024.

SELECT
  { [Measures].[Avg Data Quality] } ON COLUMNS,
  TOPCOUNT(
    [dim_city].[Geo].[country_name].Members,
    10,
    ([Measures].[Avg Data Quality], [dim_timemonth].[Time].[year_num].&[2024])
  ) ON ROWS
FROM [AirQ Cube]
WHERE ([dim_timemonth].[Time].[year_num].&[2024])

                              Avg Data Quality
region_name    country_name
Eastern Europe Belarus                    3.04
Central Europe Croatia                    3.02
Western Europe Sweden                     3.01
               Finland                    3.01
Central Europe Germany                    3.01
Western Europe Italy                      3.01
Central Europe Poland                     3.01
Western Europe France                     3.01
Eastern Europe Serbia                     3.01
Western Europe United Kingdom             3.00

### 10.7) Business question Q17

In [104]:
%%mdx 
-- 17. Show Avg Data Quality by Country for 2023 and 2024. 
-- Return Countries on rows and two columns - 2023 and 2024 values of Avg Data Quality.
    
WITH
MEMBER [Measures].[Avg_data_quality_2023] AS
    ([Measures].[Avg Data Quality], [dim_timemonth].[Time].[year_num].&[2023])
MEMBER [Measures].[Avg_data_quality_2024] AS
    ([Measures].[Avg Data Quality], [dim_timemonth].[Time].[year_num].&[2024])

SELECT
  { [Measures].[Avg_data_quality_2023], [Measures].[Avg_data_quality_2024] } ON COLUMNS,
  [dim_city].[Geo].[country_name].Members ON ROWS
FROM [AirQ Cube]

                              Avg_data_quality_2023 Avg_data_quality_2024
region_name    country_name
Central Europe Austria            2.997085641785319     2.987287890121161
               Croatia            3.042829682087076    3.0156915324857865
               Czech Republic     2.995515996615092     2.990577114224434
               Germany           3.0008475257747476    3.0108574101294594
               Hungary           3.0049301008383433    2.9990285403198667
               Poland             3.003891287578477     3.006786033180025
Eastern Europe Belarus           3.0486171863697193    3.0413258219206774
               Greece            2.9988198115907867    2.9956242531195456
               Russia             2.998203138595293    2.9952830752925657
               Serbia             2.999559974964754     3.005463363211832
               Turkey             3.008648957909837     2.997604619985246
Unknown        Unknown
Western Europe Belgium            3.015514578574743    2.9971552854165053
               Denmark           3.0217912251921906     3.000395913233702
               Finland            2.983818780808222    3.0109282905856767
               France            2.9771062445270924    3.0066534491010413
               Italy             3.0065684907853942     3.007121510088107
               Netherlands       3.0013755488963354    2.9992694126235113
               Spain               3.01792198348613     2.994293143351873
               Sweden             3.019048360132036    3.0119288648877824
               United Kingdom    3.0021892297739363     3.002515734925782

### 10.8) Business question Q28

In [105]:
%%mdx 
-- 28. For 2024, list the Top 10 Countries by Missing Days. 
-- Return the 10 countries with the highest totals on rows (highest → lowest) and one column with Missing Days for 2024.

WITH
MEMBER [Measures].[Missing_days_2024] AS
    ([Measures].[Missing Days], [dim_timemonth].[Time].[year_num].&[2024])

SELECT
  { [Measures].[Missing_days_2024] } ON COLUMNS,
  TOPCOUNT(
      FILTER(
          [dim_city].[Geo].[country_name].Members,
          [Measures].[Missing Days] > 0
      ), 10,
      [Measures].[Missing_days_2024]
  ) ON ROWS
FROM [AirQ Cube]

                              Missing_days_2024
region_name    country_name
Central Europe Germany                    19126
               Austria                    11033
Western Europe France                     10299
Eastern Europe Russia                      9299
Central Europe Czech Republic              7252
Western Europe Sweden                      6949
               Italy                       6484
               United Kingdom              5512
Central Europe Croatia                     4714
Western Europe Finland                     4573

# Student B

### 10.9) Business question Q03

In [106]:
%%mdx

-- 3. For PM10 in 2024, show the total Exceed Days (any) by City. Return one row per city and a
-- single column with the total number of exceedance days for that year.

SELECT
  { [Measures].[Exceed Days (any)] } ON COLUMNS,
        NONEMPTY(
            [dim_city].[Geo].[city_name].Members,
            [Measures].[Exceed Days (any)]
        ) ON ROWS
FROM [AirQ Cube]
WHERE (
    [dim_timemonth].[Time].[year_num].&[2024],
    [dim_param].[Param].[param_name].&[PM10]
)

                                             Exceed Days (any)
region_name    country_name   city_name
Central Europe Austria        Graz                         111
                              Salzburg                      74
                              Vienna                        77
               Croatia        Zagreb                        93
               Czech Republic Brno                          64
                              Prague                       142
               Germany        Berlin                       126
                              Hamburg                       66
                              Leipzig                        5
                              Munich                        55
                              Stuttgart                     62
               Hungary        Budapest                      90
               Poland         Warsaw                        67
Eastern Europe Belarus        Minsk                         70
               Greece         Athens                        32
               Russia         Kazan                         66
                              Moscow                       136
                              St. Petersburg                82
                              Ufa                          130
               Serbia         Belgrade                      11
               Turkey         Ankara                       125
                              Istanbul                     310
Western Europe Belgium        Brussels                      63
               Denmark        Copenhagen                    22
               Finland        Helsinki                      46
               France         Lyon                          60
                              Marseille                     31
                              Paris                        112
               Italy          Milan                         45
                              Rome                         124
               Spain          Barcelona                     65
               Sweden         Gothenburg                    93
                              Stockholm                     34
               United Kingdom Edinburgh                     66
                              London                       174

### 10.10) Business question Q06

In [107]:
%%mdx

-- 6. For 2024, list the Top 10 Cities by total Missing Days (all parameters). Return the 10 cities with
-- the highest totals on rows (highest . lowest) and one column with the 2024 total Missing Days.

SELECT
  { [Measures].[Missing Days] } ON COLUMNS,
    TOPCOUNT(
        NONEMPTY(
            [dim_city].[Geo].[city_name].Members,
            [Measures].[Missing Days]
        ),
        10, [Measures].[Missing Days]
    ) ON ROWS
FROM [AirQ Cube]
WHERE (
    [dim_timemonth].[Time].[year_num].&[2024]
)

                                        Missing Days
region_name    country_name   city_name
Central Europe Germany        Leipzig          5,194
Western Europe United Kingdom Edinburgh        5,051
Central Europe Germany        Hamburg          5,024
               Croatia        Zagreb           4,714
               Austria        Salzburg         4,672
Western Europe Finland        Helsinki         4,573
               France         Lyon             4,371
Eastern Europe Russia         Kazan            4,245
               Belarus        Minsk            4,239
Central Europe Poland         Warsaw           4,235

### 10.11) Business question Q11

In [108]:
%%mdx

-- 11. For 2024, show Exceed Days (any) by Region for Param Category = ‘Gas’. Return Regions on
-- rows and one column with Exceed Days (any) for the year 2024, filtered to Category = Gas.

WITH
MEMBER [Measures].[ExceedDays_Gas] AS
SUM(
    FILTER(
        [dim_param].[Param].[param_name].Members,
        [dim_param].[Param].CurrentMember.Parent.Name = "Gas"
    ),
    [Measures].[Exceed Days (any)]
)

SELECT
  { [Measures].[ExceedDays_Gas] } ON COLUMNS,
  NONEMPTY(
      [dim_city].[Geo].[region_name].Members,
      [Measures].[ExceedDays_Gas]
  ) ON ROWS
FROM [AirQ Cube]
WHERE [dim_timemonth].[Time].[year_num].&[2024]

               ExceedDays_Gas
region_name
Central Europe         6128.0
Eastern Europe         5742.0
Western Europe         6686.0

### 10.12) Business question Q19

In [109]:
%%mdx

-- 19. For 2024, show Missing Days and Data Volume (KB) totals by City in Central Europe. Return
-- Cities in Central Europe on rows and two columns - Missing Days and Data Volume (KB) - for
-- the year 2024.

SELECT
    { [Measures].[Missing Days],
        [Measures].[Data Volume (KB)] } ON COLUMNS,
    NONEMPTY(
        DESCENDANTS(
            [dim_city].[Geo].[region_name].&[Central Europe],
            [dim_city].[Geo].[city_name]
        ),
        [Measures].[Missing Days]
    ) ON ROWS
FROM [AirQ Cube]
WHERE (
    [dim_timemonth].[Time].[year_num].&[2024]
)

                                        Missing Days Data Volume (KB)
region_name    country_name   city_name
Central Europe Austria        Graz             3,638          435,302
                              Salzburg         4,672          444,499
                              Vienna           2,723          724,262
               Croatia        Zagreb           4,714          436,861
               Czech Republic Brno             3,751          267,548
                              Prague           3,501          630,191
               Germany        Berlin           1,757        1,067,404
                              Hamburg          5,024          434,344
                              Leipzig          5,194          399,402
                              Munich           3,644          648,363
                              Stuttgart        3,507          430,557
               Hungary        Budapest         3,221          693,174
               Poland         Warsaw           4,235          548,087

### 10.13) Business question Q24

In [110]:
%%mdx

-- 24. For parameter CO2, show P95 Recorded Value by Country for 2024. Return Countries on rows
-- and one column with P95 Recorded Value for the year 2024.

SELECT
  { [Measures].[P95 Recorded Value] } ON COLUMNS,
        NONEMPTY(
            [dim_city].[Geo].[country_name].Members,
            [Measures].[P95 Recorded Value]
        ) ON ROWS
FROM [AirQ Cube]
WHERE (
    [dim_timemonth].[Time].[year_num].&[2024],
    [dim_param].[Param].[param_name].&[CO2]
)

                              P95 Recorded Value
region_name    country_name
Central Europe Austria                    103.72
               Croatia                    112.68
               Czech Republic             127.41
               Germany                    121.85
               Hungary                     91.19
               Poland                     131.51
Eastern Europe Belarus                    129.71
               Greece                     150.90
               Russia                     113.20
               Serbia                      88.98
               Turkey                     105.20
Western Europe Belgium                    117.28
               Denmark                    107.51
               France                     104.30
               Italy                       94.27
               Netherlands                120.48
               Spain                      104.71
               Sweden                     106.31
               United Kingdom             133.03

## 11) Batch executor: run all .mdx → CSV (+ an index)

In [111]:
def run_mdx_folder(
    mdx_folder="mdx",
    out_folder="mdx_out",
    pattern="*.mdx",
    overwrite=True,
    index_csv="mdx_index.csv",
):
    mdx_path = Path(mdx_folder)
    out_path = Path(out_folder)
    mdx_path.mkdir(exist_ok=True)
    out_path.mkdir(exist_ok=True)

    records = []
    files = sorted(mdx_path.glob(pattern))
    if not files:
        print(f"No MDX files found in {mdx_path.resolve()}.")
        return pd.DataFrame()

    for f in files:
        q = f.read_text(encoding="utf-8")
        t0 = time.time()
        error = None
        rows = cols = 0
        dest = out_path / f"{f.stem}.csv"

        try:
            df = session.query_mdx(q).reset_index()
            rows, cols = df.shape
            if overwrite or not dest.exists():
                df.to_csv(dest, index=False)
        except Exception as e:
            error = str(e)

        elapsed = time.time() - t0
        records.append({
            "file": f.name,
            "csv": dest.name,
            "rows": rows,
            "cols": cols,
            "seconds": round(elapsed, 3),
            "error": error,
        })

    index_df = pd.DataFrame(records)
    index_path = out_path / index_csv
    index_df.to_csv(index_path, index=False)
    print(f"Done. Index saved to {index_path}")
    return index_df

In [112]:
# Run all MDX files:
index_df = run_mdx_folder()
index_df

Done. Index saved to mdx_out\mdx_index.csv

            file           csv  rows  cols  seconds error
0   a2_q03_B.mdx  a2_q03_B.csv    35     4    0.088  None
1   a2_q06_B.mdx  a2_q06_B.csv    10     4    0.072  None
2   a2_q07_A.mdx  a2_q07_A.csv    21     4    0.058  None
3   a2_q08_A.mdx  a2_q08_A.csv     8     3    0.062  None
4   a2_q10_A.mdx  a2_q10_A.csv    10     3    0.054  None
5   a2_q11_B.mdx  a2_q11_B.csv     3     2    0.043  None
6   a2_q17_A.mdx  a2_q17_A.csv    21     4    0.062  None
7   a2_q19_B.mdx  a2_q19_B.csv    13     5    0.075  None
8   a2_q24_B.mdx  a2_q24_B.csv    19     3    0.055  None
9   a2_q28_A.mdx  a2_q28_A.csv    10     3    0.050  None
10    a2_q31.mdx    a2_q31.csv    10     4    0.060  None
11    a2_q32.mdx    a2_q32.csv    10     4    0.070  None
12    a2_q33.mdx    a2_q33.csv    20     6    0.091  None


## 12) Create `sqldump/sqldump_airq_dwh2_xxx.sql`

We run `pg_dump -n dwh2_xxx --no-owner --no-privileges` to keep dumps portable.

In [113]:
# === Create sqldump/sqldump_airq_dwh2_xx.sql (pg_dump) ===
sqldump_dir.mkdir(exist_ok=True)
outfile = sqldump_dir / f"sqldump_airq_dwh2_{XXX}.sql"

pg_dump = shutil.which("pg_dump") or "pg_dump"
cmd = [
    pg_dump,
    "-h", DB_HOST,
    "-p", str(DB_PORT),
    "-U", DB_USER,
    "-d", DB_NAME,
    "-n", f"dwh2_{XXX}",
    "--no-owner",
    "--no-privileges",
    "-f", str(outfile),
]

# Avoid echoing the password; supply it via env if provided
env = dict(os.environ)
if 'pw' in globals() and pw:
    env["PGPASSWORD"] = pw

print("Running:", " ".join(cmd).replace(DB_USER, "<user>"))
try:
    subprocess.run(cmd, check=True, env=env)
    print("✓ Dump created at", outfile)
except Exception as e:
    print("pg_dump failed; try this manually in a terminal:\n", " ".join(cmd), "\nError:", e)

Running: C:\Program Files\PostgreSQL\17\bin\pg_dump.EXE -h localhost -p 5432 -U <user> -d airq -n dwh2_047 --no-owner --no-privileges -f D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\sqldump\sqldump_airq_dwh2_047.sql
✓ Dump created at D:\Study\Business Intelligence\Projects\DWH\BI_Projects\DWH2_047\sqldump\sqldump_airq_dwh2_047.sql

## 13) Submission checklist (put these in your **ZIP**)

- `csv/` — CSV files 
- `ddl/` — DDL scripts 
- `etl/` — Your `a2_etl*.sql` files (ETL scripts)
- `mdx/` — Your `a2_q{NN}_{A|B}.mdx` files (MDX queries for business questions)
- `mdx_out/` — Your `a2_q{NN}_{A|B}.csv` files (results of MDX queries)
- `pdf/` — Your `a2_q{NN}.pdf` files (Dashboard exports as .pdf)
- `sql/` — Your `a2_q{NN}_{A|B}.sql` files (SQL queries for business questions)
- `sqldump/` — `sqldump_airq_dwh2_xxx.sql`  
- `AirQ_Part2_xxx.ipynb`
- `group_xxx.txt`
- `Report_Part2_Group_xxx.pdf`